/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiV1CapabilitiesRouteImport } from './routes/api/v1/capabilities'
import { Route as ApiV1StatusRouteImport } from './routes/api/v1/status'
import { Route as ApiV1VersionRouteImport } from './routes/api/v1/version'
import { Route as ApiV1SessionQrBeginRouteImport } from './routes/api/v1/session/qr/begin'
import { Route as ApiV1SessionQrPollRouteImport } from './routes/api/v1/session/qr/poll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CapabilitiesRoute = ApiV1CapabilitiesRouteImport.update({
  id: '/api/v1/capabilities',
  path: '/api/v1/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatusRoute = ApiV1StatusRouteImport.update({
  id: '/api/v1/status',
  path: '/api/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VersionRoute = ApiV1VersionRouteImport.update({
  id: '/api/v1/version',
  path: '/api/v1/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionQrBeginRoute = ApiV1SessionQrBeginRouteImport.update({
  id: '/api/v1/session/qr/begin',
  path: '/api/v1/session/qr/begin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionQrPollRoute = ApiV1SessionQrPollRouteImport.update({
  id: '/api/v1/session/qr/poll',
  path: '/api/v1/session/qr/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/v1/capabilities': typeof ApiV1CapabilitiesRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/api/v1/version': typeof ApiV1VersionRoute
  '/api/v1/session/qr/begin': typeof ApiV1SessionQrBeginRoute
  '/api/v1/session/qr/poll': typeof ApiV1SessionQrPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/v1/capabilities': typeof ApiV1CapabilitiesRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/api/v1/version': typeof ApiV1VersionRoute
  '/api/v1/session/qr/begin': typeof ApiV1SessionQrBeginRoute
  '/api/v1/session/qr/poll': typeof ApiV1SessionQrPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/v1/capabilities': typeof ApiV1CapabilitiesRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/api/v1/version': typeof ApiV1VersionRoute
  '/api/v1/session/qr/begin': typeof ApiV1SessionQrBeginRoute
  '/api/v1/session/qr/poll': typeof ApiV1SessionQrPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/v1/capabilities'
    | '/api/v1/status'
    | '/api/v1/version'
    | '/api/v1/session/qr/begin'
    | '/api/v1/session/qr/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/v1/capabilities'
    | '/api/v1/status'
    | '/api/v1/version'
    | '/api/v1/session/qr/begin'
    | '/api/v1/session/qr/poll'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/v1/capabilities'
    | '/api/v1/status'
    | '/api/v1/version'
    | '/api/v1/session/qr/begin'
    | '/api/v1/session/qr/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiV1CapabilitiesRoute: typeof ApiV1CapabilitiesRoute
  ApiV1StatusRoute: typeof ApiV1StatusRoute
  ApiV1VersionRoute: typeof ApiV1VersionRoute
  ApiV1SessionQrBeginRoute: typeof ApiV1SessionQrBeginRoute
  ApiV1SessionQrPollRoute: typeof ApiV1SessionQrPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/capabilities': {
      id: '/api/v1/capabilities'
      path: '/api/v1/capabilities'
      fullPath: '/api/v1/capabilities'
      preLoaderRoute: typeof ApiV1CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/status': {
      id: '/api/v1/status'
      path: '/api/v1/status'
      fullPath: '/api/v1/status'
      preLoaderRoute: typeof ApiV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/version': {
      id: '/api/v1/version'
      path: '/api/v1/version'
      fullPath: '/api/v1/version'
      preLoaderRoute: typeof ApiV1VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/session/qr/begin': {
      id: '/api/v1/session/qr/begin'
      path: '/api/v1/session/qr/begin'
      fullPath: '/api/v1/session/qr/begin'
      preLoaderRoute: typeof ApiV1SessionQrBeginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/session/qr/poll': {
      id: '/api/v1/session/qr/poll'
      path: '/api/v1/session/qr/poll'
      fullPath: '/api/v1/session/qr/poll'
      preLoaderRoute: typeof ApiV1SessionQrPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiV1CapabilitiesRoute: ApiV1CapabilitiesRoute,
  ApiV1StatusRoute: ApiV1StatusRoute,
  ApiV1VersionRoute: ApiV1VersionRoute,
  ApiV1SessionQrBeginRoute: ApiV1SessionQrBeginRoute,
  ApiV1SessionQrPollRoute: ApiV1SessionQrPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
